#![deny(clippy::undocumented_unsafe_blocks)]

pub(crate) mod atoms {
    rustler::atoms! {
        alter_table,
        analyze,
        asc,
        atom,
        attach,
        authorization_denied,
        autoindex,
        bad_element,
        binary,
        bitstring,
        blob,
        busy,
        busy_timeout_write_refused,
        byte_size,
        bytes,
        cache_hit,
        cache_miss,
        cache_spill,
        cache_used,
        cache_used_shared,
        cache_write,
        cannot_convert_atom_to_string,
        changes,
        checkpointed_pages,
        cannot_execute,
        cannot_execute_pragma,
        cannot_open_database,
        cascade,
        category,
        code,
        columns,
        connection_closed,
        constraint_check,
        constraint_commit_hook,
        constraint_datatype,
        constraint_foreign_key,
        constraint_function,
        constraint_name,
        constraint_not_null,
        constraint_pinned,
        constraint_primary_key,
        constraint_rowid,
        constraint_trigger,
        constraint_unique,
        constraint_violation,
        constraint_vtab,
        create_index,
        create_table,
        create_temp_index,
        create_temp_table,
        create_temp_trigger,
        create_temp_view,
        create_trigger,
        create_view,
        create_vtable,
        current,
        database_busy_or_locked,
        date,
        desc,
        detach,
        detail,
        deferred,
        deferred_fks,
        done,
        duplicate_parameter_name,
        drop_index,
        drop_table,
        drop_temp_index,
        drop_temp_table,
        drop_temp_trigger,
        drop_temp_view,
        drop_trigger,
        drop_view,
        drop_vtable,
        elixir_xqlite_blob = "Elixir.Xqlite.Blob",
        error,
        expr,
        estimated_rows,
        explain,
        exclusive,
        execute_returned_results,
        expected,
        extension_loading_disabled,
        expected_keyword_list,
        expected_keyword_tuple,
        expected_list,
        improper_tail,
        filter_hit,
        filter_miss,
        float,
        from_sql_conversion_failure,
        full,
        fullscan_step,
        function,
        hidden_alias,
        id,
        immediate,
        index,
        index_exists,
        index_name,
        integer,
        integral_value_out_of_range,
        invalid_conflict_strategy,
        internal_encoding_error,
        invalid_authorizer_action,
        invalid_batch_size,
        invalid_blob_bytes,
        invalid_cancel_tokens,
        invalid_column_index,
        invalid_column_name,
        invalid_column_type,
        invalid_limit_category,
        invalid_limit_value,
        invalid_pages_per_step,
        invalid_parameter_count,
        invalid_parameter_name,
        invalid_pragma_name,
        invalid_transaction_mode,
        integer_out_of_range,
        invalid_utf8_in_string,
        invalid_stream_handle,
        list,
        limit,
        // The thirteen categories `sqlite3_limit` takes, in SQLite's own
        // order.
        length,
        sql_length,
        column,
        expr_depth,
        compound_select,
        vdbe_op,
        function_arg,
        attached,
        like_pattern_length,
        variable_number,
        trigger_depth,
        worker_threads,
        parser_depth,
        literal,
        lock_error,
        log_pages,
        lookaside_hit,
        lookaside_miss_full,
        lookaside_miss_size,
        lookaside_used,
        loops,
        map,
        memused_bytes,
        message,
        minimum,
        missing_parameter,
        multiple_statements,
        name,
        negative_infinity,
        no_action,
        no_such_index,
        no_such_table,
        no_value,
        not_a_list,
        none,
        normal,
        abort,
        null_byte_in_string,
        num_rows,
        numeric,
        observers,
        offset,
        omit,
        operation_cancelled,
        parent,
        parameters_unbound,
        parentid,
        partial,
        passive,
        pid,
        policy,
        port,
        position,
        positive_infinity,
        pragma,
        primary_key_constraint,
        provided,
        query_plan,
        read_only_database,
        read,
        reason,
        real,
        recursive,
        reference,
        reindex,
        replace,
        reprepare,
        restart,
        restrict,
        row,
        rows,
        rows_produced,
        rows_visited,
        run,
        savepoint,
        scans,
        schema_changed,
        schema_parsing_error,
        schema_used,
        select,
        selectid,
        sequence,
        set_default,
        set_null,
        shadow,
        simple,
        sort,
        source_type,
        sql,
        sql_input_error,
        sqlite_failure,
        statement_finalized,
        statement_mid_run,
        stmt_counters,
        stmt_used,
        stored_generated,
        table,
        table_exists,
        target_type,
        tempbuf_spill,
        text,
        time,
        timestamp,
        too_big,
        to_sql_conversion_failure,
        transaction,
        truncate,
        r#type = "type",
        tuple,
        value,
        value_too_large,
        value_type,
        vm_step,
        wall_time_ns,
        write,
        unexpected_value,
        unique_constraint,
        unknown,
        unsupported_atom,
        unsupported_data_type,
        utf8_error,
        r#virtual = "virtual",
        virtual_generated,
        view,
        delete,
        insert,
        update,
        xqlite_busy,
        xqlite_commit,
        xqlite_log,
        xqlite_progress,
        xqlite_rollback,
        xqlite_update,
        xqlite_wal
    }
}

mod authorizer;
mod blob;
mod busy_handler;
mod cancel;
mod commit_hook;
mod connection;
mod constraint_parse;
mod error;
mod explain_analyze;
mod hook_util;
mod limits;
mod log_hook;
mod nif;
mod pragma;
mod progress_dispatch;
mod query;
mod rollback_hook;
mod schema;
mod session;
mod statement;
mod stream;
mod transaction;
mod update_hook;
mod util;
mod wal_hook;

use rustler::{Env, Term};

fn on_load(_env: Env, _info: Term) -> bool {
    true
}

rustler::init!("Elixir.XqliteNIF", load = on_load);
