pub(crate) mod atoms {
    rustler::atoms! {
        asc,
        atom,
        autoindex,
        binary,
        blob,
        busy,
        cache_hit,
        cache_miss,
        cache_spill,
        cache_used,
        cache_used_shared,
        cache_write,
        cannot_convert_atom_to_string,
        changes,
        checkpointed_pages,
        cannot_convert_to_sqlite_value,
        cannot_execute,
        cannot_execute_pragma,
        cannot_open_database,
        cascade,
        code,
        columns,
        connection_closed,
        constraint_check,
        constraint_commit_hook,
        constraint_datatype,
        constraint_foreign_key,
        constraint_function,
        constraint_name,
        constraint_not_null,
        constraint_pinned,
        constraint_primary_key,
        constraint_rowid,
        constraint_trigger,
        constraint_unique,
        constraint_violation,
        constraint_vtab,
        create_index,
        database_busy_or_locked,
        desc,
        detail,
        deferred,
        deferred_fks,
        done,
        error,
        estimated_rows,
        explain,
        exclusive,
        execute_returned_results,
        expected,
        extension_loading_disabled,
        expected_keyword_list,
        expected_keyword_tuple,
        expected_list,
        filter_hit,
        filter_miss,
        float,
        from_sql_conversion_failure,
        full,
        fullscan_step,
        function,
        hidden_alias,
        id,
        immediate,
        index_exists,
        index_name,
        integer,
        integral_value_out_of_range,
        invalid_conflict_strategy,
        internal_encoding_error,
        invalid_batch_size,
        invalid_column_index,
        invalid_column_name,
        invalid_column_type,
        invalid_parameter_count,
        invalid_parameter_name,
        invalid_pragma_name,
        invalid_transaction_mode,
        invalid_stream_handle,
        list,
        lock_error,
        log_pages,
        lookaside_hit,
        lookaside_miss_full,
        lookaside_miss_size,
        lookaside_used,
        loops,
        map,
        memused_bytes,
        message,
        minimum,
        multiple_statements,
        name,
        no_action,
        no_such_index,
        no_such_table,
        no_value,
        none,
        normal,
        abort,
        null_byte_in_string,
        num_rows,
        numeric,
        offset,
        omit,
        operation_cancelled,
        parent,
        parentid,
        partial,
        passive,
        pid,
        port,
        primary_key_constraint,
        provided,
        query_plan,
        read_only_database,
        read,
        real,
        reference,
        replace,
        reprepare,
        restart,
        restrict,
        rows,
        rows_produced,
        rows_visited,
        run,
        scans,
        schema_changed,
        schema_parsing_error,
        schema_used,
        selectid,
        sequence,
        set_default,
        set_null,
        shadow,
        simple,
        sort,
        source_type,
        sql,
        sql_input_error,
        sqlite_failure,
        stmt_counters,
        stmt_used,
        stored_generated,
        string,
        table,
        table_exists,
        target_type,
        tempbuf_spill,
        text,
        to_sql_conversion_failure,
        truncate,
        tuple,
        vm_step,
        wall_time_ns,
        write,
        unexpected_value,
        unique_constraint,
        unknown,
        unsupported_atom,
        unsupported_data_type,
        utf8_error,
        r#virtual,
        virtual_generated,
        view,
        delete,
        insert,
        update,
        xqlite_busy,
        xqlite_log,
        xqlite_update
    }
}

mod blob;
mod busy_handler;
mod cancel;
mod connection;
mod constraint_parse;
mod error;
mod explain_analyze;
mod log_hook;
mod nif;
mod pragma;
mod query;
mod schema;
mod session;
mod stream;
mod transaction;
mod update_hook;
mod util;

use rustler::{Env, Term};

fn on_load(_env: Env, _info: Term) -> bool {
    true
}

rustler::init!("Elixir.XqliteNIF", load = on_load);
