name: Build precompiled NIFs

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.17"]
        job:
          - { target: aarch64-apple-darwin,       os: macos-14 }
          - { target: x86_64-apple-darwin,        os: macos-13 }
          - { target: aarch64-unknown-linux-gnu,   os: ubuntu-22.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl,  os: ubuntu-22.04, use-cross: true }
          - { target: riscv64gc-unknown-linux-gnu,  os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-unknown-linux-gnu,    os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-musl,   os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-pc-windows-msvc,      os: windows-latest }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project version
        shell: bash
        run: |
          VERSION=$(sed -n 's/^.*version: "\(.*\)".*/\1/p' mix.exs | head -n1)
          echo "PROJECT_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: xqlitenif
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross || false }}
          project-dir: "native/xqlitenif"

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build-crate.outputs.file-path }}
